repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
        files: ^rl-(web|internal)/.*
      - id: ruff-format
        files: ^rl-(web|internal)/.*
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.103.0
    hooks:
      - id: terraform_fmt
        files: ^terraform\/.+\.tf$
      - id: terraform_validate
        files: ^terraform\/.+\.tf$
      - id: terraform_tflint
        files: ^terraform\/.+\.tf$
