name: RL Web Deploy


on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: 146663730447.dkr.ecr.us-west-2.amazonaws.com/rocket-league-web:latest

jobs:
  get-ecs:
    name: Retrive ECS Details Managed by Terraform
    outputs:
      cluster: ${{ steps.getdetails.outputs.cluster }}
      service: ${{ steps.getdetails.outputs.service }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.4"

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Get ECS Details
        id: getdetails
        run: |
          cluster=$(terraform output -raw ecs_cluster_name)
          service=$(terraform output -raw ecs_service_name)
          echo "cluster=${cluster}" >> $GITHUB_OUTPUT
          echo "service=${service}" >> $GITHUB_OUTPUT

  deploy-ecs:
    name: Build rl-web Image and Deploy
    needs: [get-ecs]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./rl-web
          tag: ${{ env.IMAGE_NAME }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to: type=inline

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ${{ needs.get-ecs.outputs.cluster }} \
            --service ${{ needs.get-ecs.outputs.service }} \
            --force-new-deployment
